const countries=[['🇩🇿','الجزائر'],['🇧🇭','البحرين'],['🇰🇲','جزر القمر'],['🇩🇯','جيبوتي'],['🇪🇬','مصر'],['🇮🇶','العراق'],['🇯🇴','الأردن'],['🇰🇼','الكويت'],['🇱🇧','لبنان'],['🇱🇾','ليبيا'],['🇲🇷','موريتانيا'],['🇲🇦','المغرب'],['🇴🇲','عُمان'],['🇵🇸','فلسطين'],['🇶🇦','قطر'],['🇸🇦','السعودية'],['🇸🇴','الصومال'],['🇸🇩','السودان'],['🇸🇾','سوريا'],['🇹🇳','تونس'],['🇦🇪','الإمارات'],['🇾🇪','اليمن'],['🇸🇸','جنوب السودان']];
const gifts=[['🌹','وردة','1'],['🍩','دونات','30'],['💎','دايموند','1,000'],['🦁','أسد','29,999']];
let selected=[...countries.slice(0,14)], racing=false, timer=45, timerId=null, audioOn=true;
const $=s=>document.querySelector(s);
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
function renderCountries(){ $('#countryGrid').innerHTML=countries.map(([flag,name])=>`<button class="country ${selected.some(c=>c[1]===name)?'selected':''}" data-name="${name}"><span class="flag">${flag}</span><span class="country-name">${name}</span></button>`).join('');document.querySelectorAll('.country').forEach(b=>b.onclick=()=>toggleCountry(b.dataset.name)); }
function toggleCountry(name){const found=countries.find(c=>c[1]===name);if(selected.some(c=>c[1]===name)){if(selected.length===1)return;selected=selected.filter(c=>c[1]!==name)}else{if(selected.length>=14){toast('يمكن اختيار 14 دولة فقط');return}selected.push(found)}renderCountries();renderTrack();}
function renderTrack(){const list=[...selected];$('#raceTrack').innerHTML=list.map(([flag,name],i)=>`<div class="lane"><span class="lane-rank">${String(i+1).padStart(2,'0')}</span><span class="flag">${flag}</span><span class="lane-name">${name}</span><div class="lane-bar"><div class="lane-progress" style="--progress:${racing?Math.min(96,18+i*3+Math.random()*65):8+i*2}%"></div></div><span class="lane-score">${racing?Math.floor(10+Math.random()*90):'—'}</span></div>`).join('');}
function renderGifts(){ $('#giftList').innerHTML=gifts.map(([icon,name,coins])=>`<button class="gift" data-gift="${name}"><b>${icon}</b><span>${name} · ${coins}</span></button>`).join('');document.querySelectorAll('.gift').forEach(b=>b.onclick=()=>sendGift(b.dataset.gift)); }
function sendGift(gift){const c=selected[Math.floor(Math.random()*selected.length)];$('#giftFeed').innerHTML=`<span class="feed-dot"></span> أرسل @viewer_24 هدية <b>${gift}</b> لـ ${c[1]} 🎉`;toast(`تم تسجيل هدية ${gift} في السباق`);if(audioOn&&'speechSynthesis'in window){speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(`هدية ${gift} لـ ${c[1]}`))}}
function startRace(){if(racing)return;racing=true;$('#startBtn').textContent='⏸ السباق جارٍ...';$('#startBtn').disabled=true;let n=0;timerId=setInterval(()=>{n++;timer=Math.max(0,45-n);$('#roundTimer').textContent=`00:${String(timer).padStart(2,'0')}`;renderTrack();if(n>=45)finishRace()},1000);renderTrack();toast('انطلق السباق! 🏁')}
function finishRace(){clearInterval(timerId);racing=false;$('#startBtn').disabled=false;$('#startBtn').textContent='▶ ابدأ السباق';const winner=selected[Math.floor(Math.random()*selected.length)];toast(`الفائز هو ${winner[0]} ${winner[1]}! 🎉`);}
function reset(){clearInterval(timerId);racing=false;timer=45;$('#roundTimer').textContent='00:45';$('#startBtn').disabled=false;$('#startBtn').textContent='▶ ابدأ السباق';renderTrack();toast('تم تجهيز جولة جديدة')}
$('#startBtn').onclick=startRace;$('#resetBtn').onclick=reset;$('#shuffleBtn').onclick=()=>{selected.sort(()=>Math.random()-.5);renderTrack();toast('تم خلط المتسابقين')};$('#selectAllBtn').onclick=()=>{selected=[...countries.slice(0,14)];renderCountries();renderTrack();toast('تم اختيار 14 دولة')};$('#soundToggle').onclick=()=>{audioOn=!audioOn;$('#soundToggle').textContent=audioOn?'🔊':'🔇';toast(audioOn?'تم تفعيل الأصوات':'تم كتم الأصوات')};$('#connectBtn').onclick=()=>{const val=$('#usernameInput').value.trim().replace(/^@/,'');if(!val){toast('اكتب اسم مستخدم TikTok أولاً');return}$('#creatorName').textContent='@'+val;$('#connectionTag').textContent='متصل';$('#connectionTag').style.color='var(--green)';$('#connectionTag').style.background='#164538';toast('تم حفظ حساب البث التجريبي');};['#navFlags','#navLive','#navSettings'].forEach((id,i)=>$(id).onclick=()=>toast(['مكتبة الأعلام جاهزة للتعديل','أدخل بيانات TikTok لبدء الربط','الإعدادات ستتوفر في النسخة القادمة'][i]));
if ('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js').catch(()=>{});
renderCountries();renderTrack();renderGifts();setInterval(()=>{$('#viewerCount').textContent=(1248+Math.floor(Math.random()*30)).toLocaleString('en-US')},4000);
